name: Code Formatter
on: [push]
jobs:
  autoformat:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17"
      - name: Install goimports
        run: go get golang.org/x/tools/cmd/goimports
      - name: Checkout code
        uses: actions/checkout@v3
      - run: goimports -w .
      - run: go mod tidy
