name: Code Formatter
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - labeled
      - opened
      - synchronize
      - reopened
jobs:
  autoformat:
    if: github.event.action != 'labeled' || contains(github.event.pull_request.labels.*.name, 'autoformat')
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.17"
      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - name: Checkout code
        uses: actions/checkout@v3
      - run: goimports -w .
      - run: go mod tidy
      # If there are any diffs from goimports or go mod tidy, fail.
      - name: Verify no changes from goimports and go mod tidy
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            exit 1
          fi
      - name: Remove autoformat label if needed
        uses: actions/github-script@v3
        if: contains( github.event.pull_request.labels.*.name, 'autoformat')
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: 'autoformat'
            })
